# This workflow will build and push a node.js application to an Azure Web App on every push to the master branch.
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
#
# 2. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  pull_request:
    branches:
      - test

jobs:
  build-and-deploy:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: start test suite
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        ls
        chmod +x testsuite.sh
        ./testsuite.sh
